#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

# Configure Nginx to perform a 301 redirection for /redirect_me
echo 'server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 http://example.com/destination_page;
    }
}' | sudo tee /etc/nginx/sites-available/default

sudo service nginx reload