#!/usr/bin/env bash
# configure web-02 as web-01

sudo apt-get update

sudo apt-get -y install nginx

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

echo 'server {
    listen 80;
    server_name localhost;
    location / {
        root /var/www/html;
        index index.html;
    }
    add_header X-Served-By $HOSTNAME;
}' | sudo tee /etc/nginx/sites-available/default

sudo service nginx reload
