#!/usr/bin/env bash
#Display error message if less than 3 parameters used
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Accepts 4 parameters 
file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

scp_command="scp -o StrictHostKeyChecking=no -i $ssh_key_path $file_path $username@$server_ip:~/"

$scp_command
