#!/usr/bin/env bash
# Install and configure HAProxy on a new ubuntu machine

sudo apt-get update
sudo apt-get -y install haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
frontend frontweb
    bind *:80
    mode http
    timeout client 60s
    default_backend backweb
	
backend backweb
    timeout connect 10s
    timeout server 10s
    mode http
    balance roundrobin
    server web-01 54.145.240.142:80 check
    server web-02 100.26.238.188:80 check
    option http-server-close
    option forwardfor
    http-request add-header X-Served-By %[src]
EOF

sudo systemctl restart haproxy
