#!/usr/bin/env bash
# kills 7-highlander process
pid_file="/var/run/myscript.pid"
terminate() {
	echo "I hate the kill command"
	cleanup
	exit 0
}

interrupt() {
	echo "Y U no love me?!"
}

quit() {
	echo "Received SIGQUIT or SIGTERM signal. Cleaning up..."
	cleanup
	exit 0
}

cleanup() {
	rm -f "$pid_file"
}

trap 'terminate' SIGTERM
trap 'interrupt' SIGINT
trap 'quit' SIGQUIT

echo $$ > "$pid_file"

echo "To infinity and beyond"

while true; do
	sleep 1
done
