#!/usr/bin/env bash
# displays To infinity and beyond indefinitely.
process_name="4-to_infinity_and_beyond"
process_pid=$(pgrep -f "$process_name")
if [ -n "$process_pid" ]; then
	kill "$process_pid"
else
	echo "$process_name is not currently running"
fi
