#!/usr/bin/env bash
# stops 4-to_infinity_and_beyond process.
process_name="4-to_infinity_and_beyond"
if pgrep -f "$process_name" > /dev/null; then
	pkill -f "$process_name"
else
	echo "$process_name is not currently running"
fi
